ALTER TABLE "leads"
ADD COLUMN "whatsappNumber" TEXT,
ADD COLUMN "gender" TEXT,
ADD COLUMN "dateOfBirth" DATE,
ADD COLUMN "maritalStatus" TEXT,
ADD COLUMN "nationality" TEXT,
ADD COLUMN "servicesRequired" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "destinationCountries" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "highestQualification" TEXT,
ADD COLUMN "passingYear" INTEGER,
ADD COLUMN "university" TEXT,
ADD COLUMN "percentageOrCgpa" TEXT,
ADD COLUMN "currentCompany" TEXT,
ADD COLUMN "currentDesignation" TEXT,
ADD COLUMN "industry" TEXT,
ADD COLUMN "yearsOfExperience" DOUBLE PRECISION,
ADD COLUMN "currentSalary" TEXT,
ADD COLUMN "relevantExperience" TEXT,
ADD COLUMN "languageTestTaken" TEXT,
ADD COLUMN "overallScore" TEXT,
ADD COLUMN "listeningScore" TEXT,
ADD COLUMN "readingScore" TEXT,
ADD COLUMN "writingScore" TEXT,
ADD COLUMN "speakingScore" TEXT,
ADD COLUMN "passportAvailable" BOOLEAN,
ADD COLUMN "passportExpiry" DATE,
ADD COLUMN "familyMaritalStatus" TEXT,
ADD COLUMN "spouseQualification" TEXT,
ADD COLUMN "children" INTEGER,
ADD COLUMN "dependents" INTEGER,
ADD COLUMN "investmentBudget" TEXT,
ADD COLUMN "applicationTimeline" TEXT,
ADD COLUMN "resumeUrl" TEXT,
ADD COLUMN "passportDocumentUrl" TEXT,
ADD COLUMN "ieltsDocumentUrl" TEXT,
ADD COLUMN "educationalCertificateUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "experienceLetterUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "bankStatementUrl" TEXT,
ADD COLUMN "additionalInformation" TEXT,
ADD COLUMN "consentToCalls" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "termsAccepted" BOOLEAN NOT NULL DEFAULT false;
